version: '3'

services:
  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=${PGUSER}
      - POSTGRESQL_PASSWORD=${PGPASSWORD}
      - POSTGRESQL_DATABASE=${PGDATABASE}
